services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\BrandService\BrandServiceLifecycleServiceCollection:
    public: true

  provider.lifecycle.brand_service.service_collection:
    '@Ivoz\Provider\Domain\Service\BrandService\BrandServiceLifecycleServiceCollection'

  ##################################
  ## post_remove
  ##################################
  Ivoz\Provider\Domain\Service\CompanyService\RemoveByBrandService:
    tags:
      - { name: provider.lifecycle.brand_service.post_remove, priority: 10 }
    arguments:
      $companyRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\Company\\Company")'
      $companyServiceRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\CompanyService\\CompanyService")'
