services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\FaxesInOut\FaxesInOutLifecycleServiceCollection:
    public: true

  provider.lifecycle.faxes_in_out.service_collection:
    '@Ivoz\Provider\Domain\Service\FaxesInOut\FaxesInOutLifecycleServiceCollection'

  ##################################
  ## post_persist
  ##################################
  Ivoz\Provider\Domain\Service\FaxesInOut\SendFaxFile:
    tags:
      - { name: provider.lifecycle.faxes_in_out.post_persist, priority: 10}
