services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\Locution\LocutionLifecycleServiceCollection:
    public: true

  provider.lifecycle.locution.service_collection:
    '@Ivoz\Provider\Domain\Service\Locution\LocutionLifecycleServiceCollection'

  ##################################
  ## on_commit
  ##################################
  Ivoz\Provider\Domain\Service\Locution\SendRecodingOrder:
    tags:
      - { name: provider.lifecycle.locution.on_commit, priority: 10 }
    arguments:
      $recoder: '@Ivoz\Core\Infrastructure\Domain\Service\Gearman\Jobs\Recoder'