services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Provider\Domain\Service\PickUpRelUser\PickUpRelUserLifecycleServiceCollection:
    public: true

  provider.lifecycle.pick_up_rel_user.service_collection:
    '@Ivoz\Provider\Domain\Service\PickUpRelUser\PickUpRelUserLifecycleServiceCollection'

  ##################################
  ## post_persist & post_remove
  ##################################
  Ivoz\Ast\Domain\Service\PsEndpoint\UpdateByPickUpRelUser:
    tags:
      - { name: provider.lifecycle.pick_up_rel_user.post_persist, priority: 10 }
      - { name: provider.lifecycle.pick_up_rel_user.post_remove, priority: 10 }
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
